# Generated by Django 4.0.5 on 2022-06-21 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegistrationModel',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.TextField(help_text='Enter Your username', max_length=50)),
                ('user_email', models.EmailField(help_text='Enter email', max_length=50)),
                ('user_password', models.CharField(help_text='user_password', max_length=200, null=True)),
                ('user_gender', models.CharField(help_text='user_gender', max_length=200, null=True)),
                ('user_key', models.CharField(help_text='user_key', max_length=200, null=True)),
                ('user_reg_date', models.DateField(auto_now_add=True, null=True)),
                ('user_status', models.CharField(default='Pending', help_text='user_status', max_length=200)),
                ('user_upload_image', models.ImageField(help_text='user_upload_image ', max_length=50, null=True, upload_to='')),
            ],
            options={
                'db_table': 'user_registration_details',
            },
        ),
        migrations.CreateModel(
            name='UserUploadFile',
            fields=[
                ('file_id', models.AutoField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(help_text='upload_post_name', max_length=200, null=True)),
                ('file_describition', models.TextField(help_text='upload describtion', max_length=500)),
                ('file_type', models.CharField(help_text='upload_type', max_length=200, null=True)),
                ('file_size', models.CharField(help_text='upload_file', max_length=200, null=True)),
                ('file_image', models.ImageField(help_text='user_upload_image ', max_length=50, null=True, upload_to='')),
                ('user_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.userregistrationmodel')),
            ],
            options={
                'db_table': 'user_upload_files_details',
            },
        ),
    ]
