# Generated by Django 4.0.5 on 2022-06-21 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useruploadfile',
            name='file_image',
            field=models.FileField(help_text='user_upload_image ', max_length=50, null=True, upload_to=''),
        ),
    ]
