# Generated by Django 4.0.5 on 2022-06-23 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_useruploadfile_file_post_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='useruploadfile',
            name='view_rank',
            field=models.CharField(help_text='view_rank', max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='UserRequestAudit',
            fields=[
                ('audit_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_requset_audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.useruploadfile')),
            ],
            options={
                'db_table': 'user_request_audit',
            },
        ),
    ]
