# Generated by Django 4.0.5 on 2022-06-23 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_useruploadfile_view_rank_userrequestaudit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useruploadfile',
            name='view_rank',
            field=models.CharField(default=0, help_text='view_rank', max_length=200),
        ),
    ]
