# Generated by Django 4.0.5 on 2022-06-25 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0010_useruploadfile_user_audit_request_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useruploadfile',
            name='tpa_audit_request_status',
        ),
    ]
