# Generated by Django 4.0.5 on 2022-06-26 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0011_remove_useruploadfile_tpa_audit_request_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='useruploadfile',
            name='download_genrate_key',
            field=models.CharField(help_text='view_rank', max_length=200, null=True),
        ),
    ]
