# Generated by Django 4.0.5 on 2022-06-27 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0013_useruploadfile_user_download_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useruploadfile',
            name='user_download_status',
            field=models.CharField(help_text='user_download_status', max_length=200, null=True),
        ),
    ]
