# Generated by Django 4.0.5 on 2022-06-28 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0014_alter_useruploadfile_user_download_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useruploadfile',
            name='cloud_audit_request_status',
            field=models.CharField(default='Pending', help_text='cloud_audit_request_status', max_length=200),
        ),
    ]
