# Generated by Django 4.0.5 on 2022-06-28 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0015_alter_useruploadfile_cloud_audit_request_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useruploadfile',
            name='User_audit_request_status',
            field=models.CharField(default='Pending', help_text='User_audit_request_status', max_length=200),
        ),
    ]
