# Generated by Django 4.0.5 on 2022-06-29 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0016_alter_useruploadfile_user_audit_request_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useruploadfile',
            old_name='file_image',
            new_name='upload_file',
        ),
    ]
